# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2018-09-03 15:21
from __future__ import unicode_literals

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import landing_page.models
import multiselectfield.db.fields
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0008_alter_user_username_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Creator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=30, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('birthday', models.DateField(blank=True, null=True)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'abstract': False,
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=1000)),
                ('about', models.TextField(max_length=1000)),
                ('position', models.CharField(default='Not specified', max_length=1000)),
                ('url', models.CharField(default='www.website.com', max_length=100)),
                ('experience_from', models.DateField()),
                ('experience_to', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CurriculumVitae',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('freelance', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=3)),
                ('on_vacation', models.CharField(choices=[('N', 'No'), ('Y', 'Yes')], default='N', max_length=3)),
                ('vacation_till', models.DateField(blank=True, null=True)),
                ('profile', models.FileField(blank=True, null=True, upload_to=landing_page.models.user_directory_path)),
                ('address', models.CharField(max_length=1000, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128)),
                ('facebook', models.CharField(max_length=50, null=True)),
                ('linkedin', models.CharField(max_length=50, null=True)),
                ('skype', models.CharField(max_length=50, null=True)),
                ('twitter', models.CharField(max_length=50, null=True)),
                ('key_skills', models.TextField(blank=True)),
                ('about_me', models.TextField(blank=True)),
                ('resume', models.FileField(blank=True, upload_to=landing_page.models.user_directory_path)),
                ('person', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('higher_education_institution', models.CharField(max_length=100)),
                ('status', models.CharField(max_length=100)),
                ('finished', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=50)),
                ('describe', models.TextField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.CharField(max_length=20)),
                ('permissions', multiselectfield.db.fields.MultiSelectField(choices=[('Russia', 'Russia'), ('Ukraine', 'Ukraine'), ('Belarus', 'Belarus')], default='Russia', max_length=22)),
                ('travel_to_work', multiselectfield.db.fields.MultiSelectField(choices=[("Doesn't matter", "Doesn't matter"), ('Up to one hour', 'Up to one hour'), ('Up to 90 minutes', 'Up to 90 minutes')], default="Doesn't matter", max_length=46)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
