# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 18:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('level', models.CharField(max_length=10)),
                ('describe', models.TextField(blank=True)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Other',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('citizenship', models.CharField(max_length=20)),
                ('permissions', models.CharField(choices=[('Russia', 'Ru'), ('Ukraine', 'Ukr'), ('Belarus', 'Bel')], default='Russia', max_length=7)),
                ('travel_to_work', models.CharField(choices=[("Doesn't matter", "Doesn't matter"), ('Up to one hour', 'Up to one hour'), ('Up to 90 minutes', 'Up to 90 minutes')], default="Doesn't matter", max_length=50)),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
