# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-11 18:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0003_auto_20180811_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='permissions',
            field=models.CharField(choices=[('Ru', 'Russia'), ('Ukr', 'Ukraine'), ('Bel', 'Belarus')], default='Russia', max_length=7),
        ),
    ]
