# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-08-16 13:35
from __future__ import unicode_literals

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('landing_page', '0004_auto_20180811_2135'),
    ]

    operations = [
        migrations.AlterField(
            model_name='other',
            name='permissions',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('Russia', 'Russia'), ('Ukraine', 'Ukraine'), ('Belarus', 'Belarus')], default='Russia', max_length=22),
        ),
        migrations.AlterField(
            model_name='other',
            name='travel_to_work',
            field=multiselectfield.db.fields.MultiSelectField(choices=[("Doesn't matter", "Doesn't matter"), ('Up to one hour', 'Up to one hour'), ('Up to 90 minutes', 'Up to 90 minutes')], default="Doesn't matter", max_length=46),
        ),
    ]
